"""removed User.id foreign key constraint on Connection

Revision ID: 55331eb80d2d
Revises: 829e80749939
Create Date: 2025-12-11 19:06:43.442318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55331eb80d2d'
down_revision: Union[str, Sequence[str], None] = '829e80749939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('connections_user_id_fkey'), 'connections', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('connections_user_id_fkey'), 'connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
