"""add parsed to, from, cc, subject, and body for email fields

Revision ID: 78e25d3d274c
Revises: d8ba40a67383
Create Date: 2025-12-08 13:55:41.844295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e25d3d274c'
down_revision: Union[str, Sequence[str], None] = 'd8ba40a67383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('from_address', sa.String(length=512), nullable=True))
    op.add_column('messages', sa.Column('to_address', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('cc_address', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('subject', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('body', sa.Text(), nullable=True))
    op.drop_column('messages', 'raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('raw', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'body')
    op.drop_column('messages', 'subject')
    op.drop_column('messages', 'cc_address')
    op.drop_column('messages', 'to_address')
    op.drop_column('messages', 'from_address')
    # ### end Alembic commands ###
