"""add messages and syncs tables

Revision ID: 7930ac1a7cca
Revises: 70913ed0c05b
Create Date: 2025-11-23 22:51:40.609457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7930ac1a7cca'
down_revision: Union[str, Sequence[str], None] = '70913ed0c05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('label_ids', sa.JSON(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('history_id', sa.BigInteger(), nullable=True),
    sa.Column('internal_date', sa.BigInteger(), nullable=True),
    sa.Column('size_estimate', sa.BigInteger(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('syncs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='syncstatus'), nullable=False),
    sa.Column('sync_type', sa.Enum('FULL', 'INCREMENTAL', 'MANUAL', name='synctype'), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('messages_synced', sa.Integer(), nullable=False),
    sa.Column('messages_new', sa.Integer(), nullable=False),
    sa.Column('messages_updated', sa.Integer(), nullable=False),
    sa.Column('last_history_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('current_operation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncs_connection_id'), 'syncs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_syncs_status'), 'syncs', ['status'], unique=False)
    op.create_index(op.f('ix_syncs_user_id'), 'syncs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncs_user_id'), table_name='syncs')
    op.drop_index(op.f('ix_syncs_status'), table_name='syncs')
    op.drop_index(op.f('ix_syncs_connection_id'), table_name='syncs')
    op.drop_table('syncs')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
