"""oauth user_id now nullable

Revision ID: 97dfcd022c0d
Revises: f47d4c6b5a93
Create Date: 2025-12-09 18:05:53.750029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dfcd022c0d'
down_revision: Union[str, Sequence[str], None] = 'f47d4c6b5a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_states', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_oauth_states_user_id'), table_name='oauth_states')
    op.create_index(op.f('ix_oauth_states_state_token'), 'oauth_states', ['state_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_states_state_token'), table_name='oauth_states')
    op.create_index(op.f('ix_oauth_states_user_id'), 'oauth_states', ['user_id'], unique=False)
    op.alter_column('oauth_states', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
