"""add unique constraint on Message UNIQUE(user_id, external_id)


Revision ID: c738fa6161f3
Revises: 78e25d3d274c
Create Date: 2025-12-08 14:18:30.167670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c738fa6161f3'
down_revision: Union[str, Sequence[str], None] = '78e25d3d274c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_external_message', 'messages', ['user_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_external_message', 'messages', type_='unique')
    # ### end Alembic commands ###
