"""create syncs and messages tables; update connection table

Revision ID: d8ba40a67383
Revises: 7930ac1a7cca
Create Date: 2025-12-07 18:12:12.348098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ba40a67383'
down_revision: Union[str, Sequence[str], None] = '7930ac1a7cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('last_history_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'last_history_id')
    # ### end Alembic commands ###
