"""login with google user updates; no pending connection or user records

Revision ID: f47d4c6b5a93
Revises: c738fa6161f3
Create Date: 2025-12-09 17:49:12.223309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47d4c6b5a93'
down_revision: Union[str, Sequence[str], None] = 'c738fa6161f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_states', sa.Column('redirect_url', sa.String(length=2048), nullable=True))
    op.drop_constraint(op.f('oauth_states_connection_id_fkey'), 'oauth_states', type_='foreignkey')
    op.drop_column('oauth_states', 'connection_id')
    op.add_column('users', sa.Column('login_method', sa.String(length=50), nullable=False, server_default='CREDENTIALS'))
    op.add_column('users', sa.Column('oauth_provider_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_refresh_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['oauth_provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'refresh_token_expires_at')
    op.drop_column('users', 'hashed_refresh_token')
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'login_method')
    op.add_column('oauth_states', sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('oauth_states_connection_id_fkey'), 'oauth_states', 'connections', ['connection_id'], ['id'], ondelete='CASCADE')
    op.drop_column('oauth_states', 'redirect_url')
    # ### end Alembic commands ###
